---
abstract: 'set expiration headers far in the future'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-NeverExpire
requires:
  Plack: 0.9942
  Plack::Middleware: 0
  Plack::Util: 0
  Time::Piece: 0
  Time::Seconds: 0
  parent: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/Plack-Middleware-NeverExpire/issues
  homepage: http://github.com/ap/Plack-Middleware-NeverExpire
  repository: git://github.com/ap/Plack-Middleware-NeverExpire
version: 1.005
