---
abstract: 'set expiration headers far in the future'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-NeverExpire
requires:
  Plack::Middleware: 0
  Plack::Util: 0
  Time::Piece: 0
  Time::Seconds: 0
  parent: 0
resources:
  bugtracker: http://github.com/ap/Plack-Middleware-NeverExpire/issues
  homepage: http://github.com/ap/Plack-Middleware-NeverExpire
  repository: git://github.com/ap/Plack-Middleware-NeverExpire
version: 1.001
